version: "3"

services:
  server:
    image: microblogpub/microblogpub:latest 
    container_name: microblogpub
    restart: always
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"
